"""empty message

Revision ID: 710fbf417b9a
Revises:
Create Date: 2020-05-15 02:15:56.565958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710fbf417b9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
